### ISSUE TITLE
Implement Sentry

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/Halma#28]
[Sentry](https://sentry.io/) makes it easy to track errors and performance issues.

**Comment by CrazyMarvin** [comment]
I am planning to bring this game to F-Droid soon. Would Sentry be a dealbreaker, @IzzySoft?

**Comment by IzzySoft** [comment]
Nope, Sentry is FOSS and thus no deal breaker. If you set it up as opt-in, it would not even trigger an AntiFeature. You could then e.g. ask at first start to have the user agree to it to make it more widely used.

**Comment by CrazyMarvin** [comment]
Implemented in `v12.0` thanks to @Phantom-Mobile-Apps.
