### ISSUE TITLE
Vector graphics

### ISSUE THREAD

**Issue by Frosty-J** [Crazy-Marvin/Halma#29]
Hello, I believe you contacted me on Fiverr. I'm unable to reply on there - it just gives the "For privacy reasons, this user may not be contacted directly" message that, by the looks of my web search, has nothing to do with privacy.

Anyway, about SVG... libGDX doesn't support SVG, but based on the [assets](https://github.com/Crazy-Marvin/Halma/tree/development/android/assets) I think the [`ShapeRenderer`](https://libgdx.com/wiki/graphics/opengl-utils/rendering-shapes) class would work well enough for drawing simple vector graphics. I tried the [gdx-TinyVG](https://github.com/lyze237/gdx-TinyVG) library and file format before and didn't have a great experience, but it exists as a poor man's SVG equivalent.

Honestly, just having an SVG master and exporting to the required resolutions is working pretty well for myself. Scaling 0.5-1× with linear filtering looks fine. I don't think the aliasing on your assets is doing them any favours (instead of [this](https://raw.githubusercontent.com/Crazy-Marvin/Halma/development/android/assets/BluePiece.png) you could have [that](https://user-images.githubusercontent.com/60154347/176059967-364381f6-2812-4da3-aa4c-a509228ee83d.png), or preferably a white version to `setColor()` at runtime).

About other stuff... building an APK shouldn't be any bother. Will need to update `targetSdkVersion` and whatnot if you plan on uploading to [Google Play](https://developer.android.com/google/play/requirements/target-sdk). I'm a little more lost in the design department, especially since I don't find libGDX that great for creating UI-heavy stuff to begin with.

(sent you an email from `c***4@hotmail.co.uk` at 15:28 UTC)

**Comment by CrazyMarvin** [comment]
Thanks for your explanations. 👍

Let's try to optimize the assets. That should be fine.

Please contact me by [email](mailto:marvin@poopjournal.rocks) for details.

**Comment by CrazyMarvin** [comment]
Done with [Halma 6.0](https://github.com/Crazy-Marvin/Halma/releases)
